### ISSUE TITLE
Brew support

### ISSUE THREAD

**Issue by jgimeno** [dhamidi/leader#2]
I see it very useful, it would be nice to have brew support for mac.

**Comment by dhamidi** [comment]
Hey jgimeno,

that is a good suggestion, however I'm afraid that leader currently does not fullfil the requirements set by homebrew to be included in homebrew (from https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md):

> The software in question must:
> (...)
> - be known
> - be used
> (...)

I'm not that familiar with Homebrew and don't have reliable access to a Mac, so maybe you could help out with this:

- does Homebrew have a mechanism for random people on the internet to provide additional formulas (for example like PPAs work for Ubuntu)?
- if so, would you be willing to add a formula for leader?

**Comment by jgimeno** [comment]
I am not sure! I can check, maybe if I have the time I propose a PR. Thanks @dhamidi !

**Comment by dhamidi** [comment]
@jgimeno I was able to get a formula that works with https://linuxbrew.sh, haven't tested it on a Mac.

Maybe you could try:

```
brew install dhamidi/all/leader
```

Warning: That will also add `eval "$(leader init)"` to your `~/.bashrc` if it doesn't already contain such a line.

**Comment by dhamidi** [comment]
Hey @jgimeno 

Just a heads-up: if there is no movement on this issue I will close it on Monday as brew support works as far as I can tell.
